Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -70,19 +70,19 @@ for DIR in $CACHED_DIRS; do
 done
 
 # these are preliminary checks. actual version check happens below when attempting to download sbt boot.properties
-if ! test -e project/build.properties; then
-	echo " !      Error, your scala project must include project/build.properties and define sbt.version"
-	echo " !      You must use a release verison of sbt, sbt.version=0.11.0 or greater"
-        exit 1
-fi
+#if ! test -e project/build.properties; then
+#	echo " !      Error, your scala project must include project/build.properties and define sbt.version"
+#	echo " !      You must use a release verison of sbt, sbt.version=0.11.0 or greater"
+#        exit 1
+#fi
 
-if ! has_supported_sbt_version ${BUILD_DIR}; then
-	echo " !      Error, you have defined an unsupported sbt.version in project/build.properties"
-	echo " !      You must use a release verison of sbt, sbt.version=0.11.0 or greater"
-	exit 1
-fi
+#if ! has_supported_sbt_version ${BUILD_DIR}; then
+#	echo " !      Error, you have defined an unsupported sbt.version in project/build.properties"
+#	echo " !      You must use a release verison of sbt, sbt.version=0.11.0 or greater"
+#	exit 1
+#fi
  
-SBT_VERSION="$(get_supported_sbt_version ${BUILD_DIR})"
+SBT_VERSION="0.13.5"
 SBT_JAR="sbt-launch.jar"
 SBT_URL="http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.5/$SBT_JAR"
 ## in 0.10 start-script will depend on package, if packaging
